version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
  test:
    executor:
      name: node/default
      tag: '16.3'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - build
      - test