version: '2.1'
orbs:
  node: circleci/node@4.5.1
jobs:
  build:
    docker:
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: waiting for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
  test:
    executor:
      name: node/default
      tag: '16.3'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - build
      - test